### ISSUE TITLE
Doesn't compile on Elementary OS 0.4.1

### ISSUE THREAD

**Issue by patrickgue** [sgan81/apfs-fuse#59]
I want to point out, that there's a build issue with following setup: Elementary OS 0.4.1 (based on Ubuntu 16.04), x86_64, gcc 5.4.0.
The compilation stops at several header files (ApfsLib/Util.h and ApfsLib/Unicode.h) with the error message `error: 'size_t' has not been declared`.

This issue can be fixed by adding stdlib.h to these header files (`#include <stdlib.h>`). 
This is a quick and dirty solution which worked for me. Because I don't know c++ (only c) I don't know what could be the issue. 

If this appears on other operating systems as well, maybe someone should look into this.

**Comment by MaximF** [comment]
Same here on Ubuntu 16.04.5 LTS:
```
cd /home/admin/workspace/apfs-fuse/build/ApfsLib && /usr/bin/c++    -I/home/admin/workspace/apfs-fuse/. -I/home/admin/workspace/apfs-fuse/3rdparty/lzfse/src  -std=c++11 -Wall -Wextra -march=native -O3 -DNDEBUG   -std=gnu++11 -o CMakeFiles/ApfsLib.dir/Util.o -c /home/admin/workspace/apfs-fuse/ApfsLib/Util.cpp
In file included from /home/admin/workspace/apfs-fuse/ApfsLib/Util.cpp:20:0:
/home/admin/workspace/apfs-fuse/ApfsLib/Unicode.h:7:52: error: ‘size_t’ has not been declared
 void CanonicalReorder(char32_t *nfd, uint8_t *ccc, size_t len);
                                                    ^
In file included from /home/admin/workspace/apfs-fuse/3rdparty/lzfse/src/lzfse_internal.h:30:0,
                 from /home/admin/workspace/apfs-fuse/3rdparty/lzfse/src/lzvn_decode_base.h:29,
                 from /home/admin/workspace/apfs-fuse/ApfsLib/Util.cpp:41:
/home/admin/workspace/apfs-fuse/3rdparty/lzfse/src/lzfse_fse.h: In function ‘int fse_check_freq(const uint16_t*, size_t, size_t)’:
/home/admin/workspace/apfs-fuse/3rdparty/lzfse/src/lzfse_fse.h:564:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < table_size; i++) {
                     ^
ApfsLib/CMakeFiles/ApfsLib.dir/build.make:665: recipe for target 'ApfsLib/CMakeFiles/ApfsLib.dir/Util.o' failed
make[2]: *** [ApfsLib/CMakeFiles/ApfsLib.dir/Util.o] Error 1
make[2]: Leaving directory '/home/admin/workspace/apfs-fuse/build'
CMakeFiles/Makefile2:1106: recipe for target 'ApfsLib/CMakeFiles/ApfsLib.dir/all' failed
make[1]: *** [ApfsLib/CMakeFiles/ApfsLib.dir/all] Error 2
make[1]: Leaving directory '/home/admin/workspace/apfs-fuse/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by phocean** [comment]
No problem on Ubuntu 18.04, just for the memo.

**Comment by AshVoller** [comment]
Linux Mint 18.3
```
[ 23%] Building CXX object ApfsLib/CMakeFiles/ApfsLib.dir/Util.o
cd /home/vwinter/apfs-fuse/build/ApfsLib && /usr/bin/c++    -I/home/vwinter/apfs-fuse/. -I/home/vwinter/apfs-fuse/3rdparty/lzfse/src  -std=c++11 -Wall -Wextra -march=native -O3 -DNDEBUG   -std=gnu++11 -o CMakeFiles/ApfsLib.dir/Util.o -c /home/vwinter/apfs-fuse/ApfsLib/Util.cpp
In file included from /home/vwinter/apfs-fuse/ApfsLib/Util.cpp:20:0:
/home/vwinter/apfs-fuse/ApfsLib/Unicode.h:7:52: error: ‘size_t’ has not been declared
 void CanonicalReorder(char32_t *nfd, uint8_t *ccc, size_t len);
                                                    ^
In file included from /home/vwinter/apfs-fuse/3rdparty/lzfse/src/lzfse_internal.h:30:0,
                 from /home/vwinter/apfs-fuse/3rdparty/lzfse/src/lzvn_decode_base.h:29,
                 from /home/vwinter/apfs-fuse/ApfsLib/Util.cpp:41:
/home/vwinter/apfs-fuse/3rdparty/lzfse/src/lzfse_fse.h: In function ‘int fse_check_freq(const uint16_t*, size_t, size_t)’:
/home/vwinter/apfs-fuse/3rdparty/lzfse/src/lzfse_fse.h:564:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < table_size; i++) {
                     ^
ApfsLib/CMakeFiles/ApfsLib.dir/build.make:689: recipe for target 'ApfsLib/CMakeFiles/ApfsLib.dir/Util.o' failed
make[2]: *** [ApfsLib/CMakeFiles/ApfsLib.dir/Util.o] Error 1
make[2]: Leaving directory '/home/vwinter/apfs-fuse/build'
CMakeFiles/Makefile2:1106: recipe for target 'ApfsLib/CMakeFiles/ApfsLib.dir/all' failed
make[1]: *** [ApfsLib/CMakeFiles/ApfsLib.dir/all] Error 2
make[1]: Leaving directory '/home/vwinter/apfs-fuse/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sgan81** [comment]
Should be fixed.
